---
apiVersion: v1
kind: ReplicationController
metadata:
  name: govhub-landing-page
spec:
  replicas: 1
  selector:
    name: govhub-landing-page
  template:
    metadata:
      labels:
        name: govhub-landing-page
    spec:
      containers:
      - name: govhub-landing-page
        image: quay.io/ortoo/govhub-landing-page
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: govhub-landing-page
    role: service
    public: "true"
  name: govhub-landing-page
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: govhub-landing-page
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  tls:
    - secretName: governorhub-wildcard-cert
  backend:
    serviceName: govhub-landing-page
    servicePort: 80
